#!/usr/bin/perl
use strict;

# parse input
defined $ARGV[0] or die "Usage: perl muscle_iden_filter.pl OG0000573.fa.muscle minimum_identity(90) maximum_identity(100)\n";

# read MSA of fasta format, generated by muscle
my $file = shift @ARGV;
my $min_iden = shift @ARGV;
my $max_iden = shift @ARGV;
$min_iden = 90 if not $min_iden;
$max_iden = 100 if not $max_iden;
my $h;
my %aln;
open IN, "<$file" or die "Cannot open $file!\n";
while (<IN>) {
	chomp;
	if (/^>(\S+)/) {
		$h = $1;
	} else {
		$aln{$h} .= $_;
	}
}
close IN;

# parse alignment of each pair and output difference statistics
my @ids = sort keys %aln;
my ($min, $max, $sum, $num) = (100, 0, 0, 0);
my $flag = 1;
foreach my $n1 (0 .. (@ids - 2)) {
	my $a = $ids[$n1];
	foreach my $n2 (($n1 + 1) .. (@ids - 1)) {
		my $b = $ids[$n2];
		my @al = split //, $aln{$a};
		my @bl = split //, $aln{$b};
		my ($gap, $match, $mis, $iden);
		foreach my $i (0 .. (@al - 1)) {
			if ($al[$i] eq "-" or $bl[$i] eq "-") {
				$gap += 1;
			} elsif ($al[$i] eq $bl[$i]) {
				$match += 1;
			} else {
				$mis += 1;
			}
		}
		$mis = 0 if not $mis;
		$gap = 0 if not $gap;
		$iden = sprintf("%.2f", $match / ($match + $mis + $gap) * 100);
		$min = $iden if $iden < $min;
		$max = $iden if $iden > $max;
		$num += 1;
		$sum += $iden;
		#$flag = 0 if $gap / ($gap + $match + $mis) > 0.03;
		$flag = 0 if $gap > 0;
	}
}

# output MSA
#my $avg = sprintf("%.2f", $sum / $num);
#print STDOUT "$file\t$min\t$avg\t$max\n";
if ($min >= $min_iden and $max <= $max_iden) {
#if ($flag == 1) {
	#print STDERR "$file\n";
	#print STDERR "Identity_range(%): $min - $max\n";
	open OUT, ">${file}.filtered" or die "$!\n";
	foreach $h (@ids) {
		print OUT ">$h\n$aln{$h}\n";
	}
	close OUT;
}
