#!/usr/bin/perl
use strict;

# parse input
defined $ARGV[0] or die "Usage: perl muscle2diff.pl OG0000819.fa.muscle > OG0000819.fa.muscle.diff\n";

# read MSA of fasta format, generated by muscle
#my $homo = $ARGV[1];
#$homo = 6 if not defined $homo;
my $h;
my %aln;
my %freq;
open IN, "<$ARGV[0]" or die "Cannot open $ARGV[0]!\n";
while (<IN>) {
	chomp;
	if (/^>(\S+)/) {
		$h = $1;
		my @t = split /:/, $h;
		$freq{$t[0]} = 1;
	} else {
		$aln{$h} .= $_;
	}
}
close IN;
#my $n = keys %freq;
#die "Maybe duplicated genes locate in the same contig!\n" if $n < $homo;

# parse alignment of each pair and output difference statistics
my @ids = sort keys %aln;
print "#Seqa_vs_b\tLength_a\tLength_b\tMatches\tMismatches\tInsertion_a\tInsertion_b\tIdentity_a\tIdentity_b\tIdentity_overall\n";
foreach my $n1 (0 .. (@ids - 2)) {
	my $a = $ids[$n1];
	foreach my $n2 (($n1 + 1) .. (@ids - 1)) {
		my $b = $ids[$n2];
		my @al = split //, $aln{$a};
		my @bl = split //, $aln{$b};
		my ($lena, $lenb, $match, $mis, $ina, $inb, $idena, $idenb, $iden);
		foreach my $i (0 .. (@al - 1)) {
			if ($al[$i] eq "-" and $bl[$i] eq "-") {
				next;
			} elsif ($al[$i] eq "-") {
				$inb += 1;
				$lenb += 1;
			} elsif ($bl[$i] eq "-") {
				$ina += 1;
				$lena += 1;
			} elsif ($al[$i] eq $bl[$i]) {
				$match += 1;
				$lena += 1;
				$lenb += 1;
			} else {
				$mis += 1;
				$lena += 1;
				$lenb += 1;
			}
		}
		$idena = sprintf("%.2f", $match / $lena * 100);
		$idenb = sprintf("%.2f", $match / $lenb * 100);
		$mis = 0 if not $mis;
		#$iden = sprintf("%.2f", $match / ($match + $mis) * 100);
		$iden = sprintf("%.2f", $match * 2 / ($lena + $lenb) * 100);
		$ina = 0 if not $ina;
		$inb = 0 if not $inb;
		print "${a}_vs_${b}\t$lena\t$lenb\t$match\t$mis\t$ina\t$inb\t$idena\t$idenb\t$iden\n";
	}
}
